import type {
  ActivityItem,
  Asset,
  LocationItem,
  MaintenanceItem,
  ReservationItem,
  UserItem,
} from './types';

export const assets: Asset[] = [
  {
    id: 'asset-001',
    name: 'MacBook Pro 14 M3',
    category: 'Laptop',
    location: 'Hauptlager',
    status: 'Verfuegbar',
    assignedTo: '-',
    nextReturn: '-',
    tagNumber: 'HW-1001',
    serialNumber: 'C02XJ1A9MD6T',
    maintenanceState: 'Geprueft am 03.03.2026',
    notes: 'Standard-Deployment, 16 GB RAM, 512 GB SSD.',
    lastCheckout: '28.02.2026',
    nextReservation: '12.03.2026 - Marketing Team',
  },
  {
    id: 'asset-002',
    name: 'Epson WorkForce Pro',
    category: 'Drucker',
    location: 'Buero',
    status: 'Ausgegeben',
    assignedTo: 'IT-Support',
    nextReturn: '10.03.2026',
    tagNumber: 'HW-1042',
    serialNumber: 'EP-7XA2-441',
    maintenanceState: 'Toner tauschen geplant',
    notes: 'Nutzt Duplex standardmaessig, WLAN deaktiviert.',
    lastCheckout: '05.03.2026',
    nextReservation: '11.03.2026 - Finance',
  },
  {
    id: 'asset-003',
    name: 'Zebra DS2278',
    category: 'QR-Code-Scanner',
    location: 'Eventlager',
    status: 'Reserviert',
    assignedTo: 'Event-Team Nord',
    nextReturn: '13.03.2026',
    tagNumber: 'HW-2104',
    serialNumber: 'ZB-442-98XA',
    maintenanceState: 'Alles OK',
    notes: 'Wireless Docking Station inklusive.',
    lastCheckout: '20.02.2026',
    nextReservation: '09.03.2026 - Messe Hamburg',
  },
  {
    id: 'asset-004',
    name: 'Honeywell CT30 XP',
    category: 'Handscanner',
    location: 'Fahrzeug 2',
    status: 'Unterwegs',
    assignedTo: 'Roadshow Team',
    nextReturn: '09.03.2026',
    tagNumber: 'HW-3109',
    serialNumber: 'HWL-CT30-771',
    maintenanceState: 'Batterie 84%',
    notes: 'Transportkoffer mit Ladegeraet beigelegt.',
    lastCheckout: '02.03.2026',
    nextReservation: '15.03.2026 - Service Team',
  },
  {
    id: 'asset-005',
    name: 'iPad Air 11',
    category: 'Tablet',
    location: 'Ausseneinsatz',
    status: 'In Wartung',
    assignedTo: 'Werkstatt',
    nextReturn: 'Unbekannt',
    tagNumber: 'HW-1217',
    serialNumber: 'IPA-4TH-2026',
    maintenanceState: 'Displayreparatur laeuft',
    notes: 'Display gesprungen nach Event-Aufbau.',
    lastCheckout: '21.02.2026',
    nextReservation: '-',
  },
  {
    id: 'asset-006',
    name: 'Dell Latitude 7440',
    category: 'Laptop',
    location: 'Hauptlager',
    status: 'Defekt',
    assignedTo: '-',
    nextReturn: '-',
    tagNumber: 'HW-1129',
    serialNumber: 'DL-7440-991',
    maintenanceState: 'Mainboard pruefen',
    notes: 'Startet nicht mehr, Boot-Loop.',
    lastCheckout: '11.02.2026',
    nextReservation: '-',
  },
  {
    id: 'asset-007',
    name: 'Lenovo ThinkPad E16',
    category: 'Laptop',
    location: 'Hauptlager',
    status: 'Verfuegbar',
    assignedTo: '-',
    nextReturn: '-',
    tagNumber: 'HW-1180',
    serialNumber: 'LN-E16-5642',
    maintenanceState: 'Geprueft am 08.03.2026',
    notes: 'Neu eingelagert nach Leasing-Ruecklauf.',
    lastCheckout: '17.01.2026',
    nextReservation: '-',
  },
  {
    id: 'asset-008',
    name: 'Atem Mini Pro ISO',
    category: 'Event-Technik',
    location: 'Eventlager',
    status: 'Reserviert',
    assignedTo: 'Live Production',
    nextReturn: '16.03.2026',
    tagNumber: 'HW-4501',
    serialNumber: 'ATEM-ISO-090',
    maintenanceState: 'Firmware aktuell',
    notes: 'Wird mit HDMI-Set und Netzteil ausgegeben.',
    lastCheckout: '01.03.2026',
    nextReservation: '10.03.2026 - Produktlaunch',
  },
  {
    id: 'asset-009',
    name: 'Samsung Galaxy Tab S9',
    category: 'Tablet',
    location: 'Buero',
    status: 'Ausgegeben',
    assignedTo: 'Vertrieb',
    nextReturn: '08.03.2026 (ueberfaellig)',
    tagNumber: 'HW-1364',
    serialNumber: 'SGS9-213-AA',
    maintenanceState: 'Rueckgabe offen',
    notes: 'Wird fuer mobile Signaturprozesse genutzt.',
    lastCheckout: '25.02.2026',
    nextReservation: '12.03.2026 - Sales Ops',
  },
  {
    id: 'asset-010',
    name: 'Brother ADS-4700W',
    category: 'Scanner',
    location: 'Werkstatt',
    status: 'Verloren',
    assignedTo: 'Externer Dienstleister',
    nextReturn: 'Nicht planbar',
    tagNumber: 'HW-1708',
    serialNumber: 'BR-ADS-4700W',
    maintenanceState: 'Meldung geoeffnet',
    notes: 'Transportstatus seit 14 Tagen unklar.',
    lastCheckout: '15.02.2026',
    nextReservation: '-',
  },
];

export const activities: ActivityItem[] = [
  {
    id: 'act-1',
    title: 'Check-out abgeschlossen',
    detail: 'MacBook Pro 14 M3 wurde an Design Team ausgegeben.',
    timestamp: 'Heute, 08:42',
    assetId: 'asset-001',
  },
  {
    id: 'act-2',
    title: 'Rueckgabe erhalten',
    detail: 'Zebra DS2278 eingelagert und geprueft.',
    timestamp: 'Heute, 09:16',
    assetId: 'asset-003',
  },
  {
    id: 'act-3',
    title: 'Defekt gemeldet',
    detail: 'Dell Latitude 7440 startet nicht mehr.',
    timestamp: 'Heute, 10:05',
    assetId: 'asset-006',
  },
  {
    id: 'act-4',
    title: 'Reservierung bestaetigt',
    detail: 'Atem Mini Pro ISO fuer Produktlaunch fixiert.',
    timestamp: 'Heute, 10:44',
    assetId: 'asset-008',
  },
  {
    id: 'act-5',
    title: 'Wartung gestartet',
    detail: 'iPad Air 11 in Werkstatt uebergeben.',
    timestamp: 'Heute, 11:12',
    assetId: 'asset-005',
  },
];

export const reservations: ReservationItem[] = [
  {
    id: 'res-2001',
    requestedBy: 'Anna Weiss',
    team: 'Marketing Team',
    period: '12.03.2026 - 14.03.2026',
    assets: ['MacBook Pro 14 M3', 'Samsung Galaxy Tab S9'],
    status: 'Bestaetigt',
    location: 'Messe Berlin',
  },
  {
    id: 'res-2002',
    requestedBy: 'Luca Berger',
    team: 'Event-Team Nord',
    period: '09.03.2026 - 13.03.2026',
    assets: ['Zebra DS2278', 'Atem Mini Pro ISO'],
    status: 'Aktiv',
    location: 'Hamburg Messehalle A2',
  },
  {
    id: 'res-2003',
    requestedBy: 'Sophie Klein',
    team: 'Finance',
    period: '11.03.2026 - 11.03.2026',
    assets: ['Epson WorkForce Pro'],
    status: 'Angefragt',
    location: 'HQ Besprechungsraum 3',
  },
  {
    id: 'res-2004',
    requestedBy: 'Mert Kaya',
    team: 'Roadshow Team',
    period: '15.03.2026 - 17.03.2026',
    assets: ['Honeywell CT30 XP', 'Lenovo ThinkPad E16'],
    status: 'Bestaetigt',
    location: 'Koeln Innenstadt',
  },
  {
    id: 'res-2005',
    requestedBy: 'Nina Roth',
    team: 'Operations',
    period: '07.03.2026 - 08.03.2026',
    assets: ['Brother ADS-4700W'],
    status: 'Storniert',
    location: 'Externes Lager',
  },
];

export const maintenanceItems: MaintenanceItem[] = [
  {
    id: 'mnt-01',
    assetName: 'iPad Air 11',
    issue: 'Displaybruch links unten',
    reportedAt: '04.03.2026',
    dueDate: '11.03.2026',
    priority: 'Hoch',
    status: 'In Arbeit',
    comment: 'Ersatzteil bestellt, Einbau fuer Dienstag geplant.',
    location: 'Werkstatt',
  },
  {
    id: 'mnt-02',
    assetName: 'Dell Latitude 7440',
    issue: 'Boot-Loop / kein POST',
    reportedAt: '06.03.2026',
    dueDate: '12.03.2026',
    priority: 'Kritisch',
    status: 'Offen',
    comment: 'Diagnose durch externen Service erforderlich.',
    location: 'Hauptlager',
  },
  {
    id: 'mnt-03',
    assetName: 'Epson WorkForce Pro',
    issue: 'Toner fast leer',
    reportedAt: '05.03.2026',
    dueDate: '09.03.2026',
    priority: 'Mittel',
    status: 'Wartet auf Teile',
    comment: 'Lieferung im Zulauf, Tracking aktiv.',
    location: 'Buero',
  },
  {
    id: 'mnt-04',
    assetName: 'Brother ADS-4700W',
    issue: 'Transportverlust',
    reportedAt: '23.02.2026',
    dueDate: '10.03.2026',
    priority: 'Kritisch',
    status: 'Offen',
    comment: 'Schadensfall bei Logistikpartner eroeffnet.',
    location: 'Ausseneinsatz',
  },
];

export const locations: LocationItem[] = [
  {
    name: 'Hauptlager',
    capacity: '220 Slots',
    assignedAssets: 128,
    availableAssets: 87,
    manager: 'Nils Kramer',
  },
  {
    name: 'Eventlager',
    capacity: '140 Slots',
    assignedAssets: 91,
    availableAssets: 21,
    manager: 'Lara Meier',
  },
  {
    name: 'Fahrzeug 2',
    capacity: '32 Slots',
    assignedAssets: 24,
    availableAssets: 4,
    manager: 'Roadshow Team',
  },
  {
    name: 'Ausseneinsatz',
    capacity: 'Variable',
    assignedAssets: 18,
    availableAssets: 0,
    manager: 'Field Ops',
  },
  {
    name: 'Buero',
    capacity: '70 Slots',
    assignedAssets: 52,
    availableAssets: 9,
    manager: 'Office IT',
  },
  {
    name: 'Werkstatt',
    capacity: '40 Slots',
    assignedAssets: 16,
    availableAssets: 3,
    manager: 'Service Team',
  },
];

export const users: UserItem[] = [
  {
    id: 'usr-01',
    name: 'Nils Kramer',
    email: 'nils.kramer@atlasops.io',
    role: 'Admin',
    lastActive: 'Heute, 11:25',
    status: 'Aktiv',
  },
  {
    id: 'usr-02',
    name: 'Lara Meier',
    email: 'lara.meier@atlasops.io',
    role: 'Lager / Logistik',
    lastActive: 'Heute, 10:58',
    status: 'Aktiv',
  },
  {
    id: 'usr-03',
    name: 'Anna Weiss',
    email: 'anna.weiss@atlasops.io',
    role: 'Mitarbeiter',
    lastActive: 'Heute, 09:40',
    status: 'Aktiv',
  },
  {
    id: 'usr-04',
    name: 'Mert Kaya',
    email: 'mert.kaya@atlasops.io',
    role: 'Event-Team',
    lastActive: 'Heute, 08:17',
    status: 'Aktiv',
  },
  {
    id: 'usr-05',
    name: 'Finance Viewer',
    email: 'finance.viewer@atlasops.io',
    role: 'Nur-Lesen',
    lastActive: 'Gestern, 17:32',
    status: 'Eingeschraenkt',
  },
];
